# Generated by Django 3.1.3 on 2020-11-03 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('identity_document_number', models.CharField(max_length=50, unique=True)),
                ('date_of_birth', models.DateField()),
            ],
        ),
    ]
